name: Install Common Deps for UniFFI Tasks
runs:
  using: composite
  steps:
    - name: Install cargo-make
      uses: taiki-e/install-action@6cd13508893c0e7eab5f273c2575d3859bd7229a # v2.86.6
      with: { tool: cargo-make@0.37 }
